
name: Library Release PCM

on:
  release:
    branches: [main]
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Tag Name
        id: tagName
        uses: olegtarasov/get-tag@v2.1.2
        with:
          tagRegex: "foobar-(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
          tagRegexGroup: 1 # Optional. Default is 1.

      - name: Some other step # Output usage example
        run: echo "Tag Name: $GIT_TAG_NAME"

      - name: Yet another step # Environment variable usage example
        run: python3 ../../package.py $GIT_TAG_NAME

      - name: Upload files to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: espressif-kicad-addon
          path: build/espressif-kicad-addon.zip
