name: Library Release PCM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Tag Name
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName

      - name: Get the release tag
        with:
          tagname: ${{ steps.tagName.outputs.tag }}
        run: "echo tagName: ${{ steps.tagName.outputs.tag }}"

      - name: Run the PCM Python script
        run: |
          ls
          python3 package.py $GIT_TAG_NAME

      - name: Upload files to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: espressif-kicad-addon
          path: build/espressif-kicad-addon.zip
