
name: Library Release PCM

on:
  release:
    branches: [main]
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Tag Name
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName

      - name: Some other step # Output usage example
        run: echo "Tag Name $GIT_TAG_NAME"

      - name: Yet another step # Environment variable usage example
        run: python3 ${{ github.workspace }}/package.py $GIT_TAG_NAME

      - name: Upload files to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: espressif-kicad-addon
          path: ${{ github.workspace }}/build/espressif-kicad-addon.zip
