name: Library Release PCM

on:
  release:
    branches: [main]
    types:
      - published
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Tag Name
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName

      - name: Create the PCM package
        run: |
          echo "Release tag $GIT_TAG_NAME"
          python3 package.py $GIT_TAG_NAME

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          asset_path: build
          asset_name: espressif-kicad-addon.zip
          asset_content_type: application/octet-stream
          release_tag: $GIT_TAG_NAME
          github_token: ${{ secrets.GITHUB_TOKEN }}
